// @generated by protoc-gen-es v1.3.1 with parameter "target=ts,import_extension=none"
// @generated from file recorder/provider.proto (package recorder, syntax proto3)
/* eslint-disable */
// @ts-nocheck
import { Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { RoundRecord, ShiftRecord, ShuffleRecord, URLMedia } from "./record_pb";
/**
 * @generated from message recorder.RecordQuery
 */
export class RecordQuery extends Message {
    /**
     * 查詢起時
     *
     * @generated from field: google.protobuf.Timestamp ts_from = 1;
     */
    tsFrom;
    /**
     * 查詢終時
     *
     * @generated from field: google.protobuf.Timestamp ts_to = 2;
     */
    tsTo;
    /**
     * 筆數
     *
     * @generated from field: optional int64 limit = 3;
     */
    limit;
    /**
     * 頁面
     *
     * @generated from field: optional int64 page = 4;
     */
    page;
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.RecordQuery";
    static fields = proto3.util.newFieldList(() => [
        { no: 1, name: "ts_from", kind: "message", T: Timestamp },
        { no: 2, name: "ts_to", kind: "message", T: Timestamp },
        { no: 3, name: "limit", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
        { no: 4, name: "page", kind: "scalar", T: 3 /* ScalarType.INT64 */, opt: true },
    ]);
    static fromBinary(bytes, options) {
        return new RecordQuery().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new RecordQuery().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new RecordQuery().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(RecordQuery, a, b);
    }
}
/**
 * @generated from message recorder.FetchShiftRecordRequest
 */
export class FetchShiftRecordRequest extends Message {
    /**
     * 紀錄ID
     *
     * @generated from field: optional bytes record_id = 1;
     */
    recordId;
    /**
     * 遊戲類型
     *
     * @generated from field: optional string game_type = 2;
     */
    gameType;
    /**
     * 遊戲子類型
     *
     * @generated from field: optional string game_subtype = 3;
     */
    gameSubtype;
    /**
     * 遊戲代碼
     *
     * @generated from field: optional string game_code = 5;
     */
    gameCode;
    /**
     * 桌代碼
     *
     * @generated from field: optional string table_code = 6;
     */
    tableCode;
    /**
     * 允許的紀錄ID
     *
     * @generated from field: repeated bytes record_ids = 9;
     */
    recordIds = [];
    /**
     * 允許的遊戲類型
     *
     * @generated from field: repeated string game_types = 10;
     */
    gameTypes = [];
    /**
     * 允許的遊戲子類型
     *
     * @generated from field: repeated string game_subtypes = 11;
     */
    gameSubtypes = [];
    /**
     * 允許的遊戲代碼
     *
     * @generated from field: repeated string game_codes = 13;
     */
    gameCodes = [];
    /**
     * 允許的桌代碼
     *
     * @generated from field: repeated string table_codes = 14;
     */
    tableCodes = [];
    /**
     * 查詢限制
     *
     * @generated from field: recorder.RecordQuery query = 20;
     */
    query;
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.FetchShiftRecordRequest";
    static fields = proto3.util.newFieldList(() => [
        { no: 1, name: "record_id", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
        { no: 2, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 3, name: "game_subtype", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 5, name: "game_code", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 6, name: "table_code", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 9, name: "record_ids", kind: "scalar", T: 12 /* ScalarType.BYTES */, repeated: true },
        { no: 10, name: "game_types", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 11, name: "game_subtypes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 13, name: "game_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 14, name: "table_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 20, name: "query", kind: "message", T: RecordQuery },
    ]);
    static fromBinary(bytes, options) {
        return new FetchShiftRecordRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new FetchShiftRecordRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new FetchShiftRecordRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(FetchShiftRecordRequest, a, b);
    }
}
/**
 * @generated from message recorder.FetchShiftRecordResponse
 */
export class FetchShiftRecordResponse extends Message {
    /**
     * @generated from field: repeated recorder.ShiftRecord shift_record = 1;
     */
    shiftRecord = [];
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.FetchShiftRecordResponse";
    static fields = proto3.util.newFieldList(() => [
        { no: 1, name: "shift_record", kind: "message", T: ShiftRecord, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new FetchShiftRecordResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new FetchShiftRecordResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new FetchShiftRecordResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(FetchShiftRecordResponse, a, b);
    }
}
/**
 * @generated from message recorder.FetchShuffleRecordRequest
 */
export class FetchShuffleRecordRequest extends Message {
    /**
     * 紀錄ID
     *
     * @generated from field: optional bytes record_id = 1;
     */
    recordId;
    /**
     * 遊戲類型
     *
     * @generated from field: optional string game_type = 2;
     */
    gameType;
    /**
     * 遊戲子類型
     *
     * @generated from field: optional string game_subtype = 3;
     */
    gameSubtype;
    /**
     * 遊戲代碼
     *
     * @generated from field: optional string game_code = 5;
     */
    gameCode;
    /**
     * 桌代碼
     *
     * @generated from field: optional string table_code = 6;
     */
    tableCode;
    /**
     * 班代碼
     *
     * @generated from field: optional string shift_code = 7;
     */
    shiftCode;
    /**
     * 洗牌代碼
     *
     * @generated from field: optional string shuffle_code = 8;
     */
    shuffleCode;
    /**
     * 允許的紀錄ID
     *
     * @generated from field: repeated bytes record_ids = 9;
     */
    recordIds = [];
    /**
     * 允許的遊戲類型
     *
     * @generated from field: repeated string game_types = 10;
     */
    gameTypes = [];
    /**
     * 允許的遊戲子類型
     *
     * @generated from field: repeated string game_subtypes = 11;
     */
    gameSubtypes = [];
    /**
     * 允許的遊戲代碼
     *
     * @generated from field: repeated string game_codes = 13;
     */
    gameCodes = [];
    /**
     * 允許的桌代碼
     *
     * @generated from field: repeated string table_codes = 14;
     */
    tableCodes = [];
    /**
     * 允許的班代碼
     *
     * @generated from field: repeated string shift_codes = 15;
     */
    shiftCodes = [];
    /**
     * 允許的洗牌代碼
     *
     * @generated from field: repeated string shuffle_codes = 16;
     */
    shuffleCodes = [];
    /**
     * 查詢限制
     *
     * @generated from field: recorder.RecordQuery query = 20;
     */
    query;
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.FetchShuffleRecordRequest";
    static fields = proto3.util.newFieldList(() => [
        { no: 1, name: "record_id", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
        { no: 2, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 3, name: "game_subtype", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 5, name: "game_code", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 6, name: "table_code", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 7, name: "shift_code", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 8, name: "shuffle_code", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 9, name: "record_ids", kind: "scalar", T: 12 /* ScalarType.BYTES */, repeated: true },
        { no: 10, name: "game_types", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 11, name: "game_subtypes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 13, name: "game_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 14, name: "table_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 15, name: "shift_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 16, name: "shuffle_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 20, name: "query", kind: "message", T: RecordQuery },
    ]);
    static fromBinary(bytes, options) {
        return new FetchShuffleRecordRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new FetchShuffleRecordRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new FetchShuffleRecordRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(FetchShuffleRecordRequest, a, b);
    }
}
/**
 * @generated from message recorder.FetchShuffleRecordResponse
 */
export class FetchShuffleRecordResponse extends Message {
    /**
     * @generated from field: repeated recorder.ShuffleRecord shuffle_record = 1;
     */
    shuffleRecord = [];
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.FetchShuffleRecordResponse";
    static fields = proto3.util.newFieldList(() => [
        { no: 1, name: "shuffle_record", kind: "message", T: ShuffleRecord, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new FetchShuffleRecordResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new FetchShuffleRecordResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new FetchShuffleRecordResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(FetchShuffleRecordResponse, a, b);
    }
}
/**
 * @generated from message recorder.FetchRoundRecordRequest
 */
export class FetchRoundRecordRequest extends Message {
    /**
     * 紀錄ID
     *
     * @generated from field: optional bytes record_id = 1;
     */
    recordId;
    /**
     * 遊戲類型
     *
     * @generated from field: optional string game_type = 2;
     */
    gameType;
    /**
     * 遊戲子類型
     *
     * @generated from field: optional string game_subtype = 3;
     */
    gameSubtype;
    /**
     * 遊戲代碼
     *
     * @generated from field: optional string game_code = 5;
     */
    gameCode;
    /**
     * 桌代碼
     *
     * @generated from field: optional string table_code = 6;
     */
    tableCode;
    /**
     * 班代碼
     *
     * @generated from field: optional string shift_code = 7;
     */
    shiftCode;
    /**
     * 局代碼
     *
     * @generated from field: optional string round_code = 8;
     */
    roundCode;
    /**
     * 允許的紀錄ID
     *
     * @generated from field: repeated bytes record_ids = 9;
     */
    recordIds = [];
    /**
     * 允許的遊戲類型
     *
     * @generated from field: repeated string game_types = 10;
     */
    gameTypes = [];
    /**
     * 允許的遊戲子類型
     *
     * @generated from field: repeated string game_subtypes = 11;
     */
    gameSubtypes = [];
    /**
     * 允許的遊戲代碼
     *
     * @generated from field: repeated string game_codes = 13;
     */
    gameCodes = [];
    /**
     * 允許的桌代碼
     *
     * @generated from field: repeated string table_codes = 14;
     */
    tableCodes = [];
    /**
     * 允許的班代碼
     *
     * @generated from field: repeated string shift_codes = 15;
     */
    shiftCodes = [];
    /**
     * 允許的局代碼
     *
     * @generated from field: repeated string round_codes = 16;
     */
    roundCodes = [];
    /**
     * 查詢限制
     *
     * @generated from field: recorder.RecordQuery query = 20;
     */
    query;
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.FetchRoundRecordRequest";
    static fields = proto3.util.newFieldList(() => [
        { no: 1, name: "record_id", kind: "scalar", T: 12 /* ScalarType.BYTES */, opt: true },
        { no: 2, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 3, name: "game_subtype", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 5, name: "game_code", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 6, name: "table_code", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 7, name: "shift_code", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 8, name: "round_code", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
        { no: 9, name: "record_ids", kind: "scalar", T: 12 /* ScalarType.BYTES */, repeated: true },
        { no: 10, name: "game_types", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 11, name: "game_subtypes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 13, name: "game_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 14, name: "table_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 15, name: "shift_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 16, name: "round_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 20, name: "query", kind: "message", T: RecordQuery },
    ]);
    static fromBinary(bytes, options) {
        return new FetchRoundRecordRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new FetchRoundRecordRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new FetchRoundRecordRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(FetchRoundRecordRequest, a, b);
    }
}
/**
 * @generated from message recorder.FetchRoundRecordResponse
 */
export class FetchRoundRecordResponse extends Message {
    /**
     * @generated from field: repeated recorder.RoundRecord round_record = 1;
     */
    roundRecord = [];
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.FetchRoundRecordResponse";
    static fields = proto3.util.newFieldList(() => [
        { no: 1, name: "round_record", kind: "message", T: RoundRecord, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new FetchRoundRecordResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new FetchRoundRecordResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new FetchRoundRecordResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(FetchRoundRecordResponse, a, b);
    }
}
/**
 * 遊戲供應
 *
 * @generated from message recorder.GameProvide
 */
export class GameProvide extends Message {
    /**
     * 遊戲類型
     *
     * @generated from field: string game_type = 2;
     */
    gameType = "";
    /**
     * 遊戲子類型
     *
     * @generated from field: string game_subtype = 3;
     */
    gameSubtype = "";
    /**
     * 遊戲代碼
     *
     * @generated from field: string game_code = 4;
     */
    gameCode = "";
    /**
     * 標籤
     *
     * @generated from field: map<string, string> tags = 5;
     */
    tags = {};
    /**
     * 維護中
     *
     * @generated from field: bool maintenance = 7;
     */
    maintenance = false;
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.GameProvide";
    static fields = proto3.util.newFieldList(() => [
        { no: 2, name: "game_type", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 3, name: "game_subtype", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 4, name: "game_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 5, name: "tags", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "scalar", T: 9 /* ScalarType.STRING */ } },
        { no: 7, name: "maintenance", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    ]);
    static fromBinary(bytes, options) {
        return new GameProvide().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new GameProvide().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new GameProvide().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(GameProvide, a, b);
    }
}
/**
 * @generated from message recorder.FetchGameProvideListResponse
 */
export class FetchGameProvideListResponse extends Message {
    /**
     * 桌列表
     *
     * @generated from field: repeated recorder.GameProvide game_provides = 1;
     */
    gameProvides = [];
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.FetchGameProvideListResponse";
    static fields = proto3.util.newFieldList(() => [
        { no: 1, name: "game_provides", kind: "message", T: GameProvide, repeated: true },
    ]);
    static fromBinary(bytes, options) {
        return new FetchGameProvideListResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new FetchGameProvideListResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new FetchGameProvideListResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(FetchGameProvideListResponse, a, b);
    }
}
/**
 * @generated from message recorder.CurrentGame
 */
export class CurrentGame extends Message {
    /**
     * 遊戲代碼
     *
     * @generated from field: string game_code = 5;
     */
    gameCode = "";
    /**
     * 班
     *
     * @generated from field: optional recorder.ShiftRecord shift = 7;
     */
    shift;
    /**
     * 遊戲局
     *
     * @generated from field: optional recorder.RoundRecord round = 9;
     */
    round;
    /**
     * 洗牌
     *
     * @generated from field: optional recorder.ShuffleRecord shuffle = 10;
     */
    shuffle;
    /**
     * 附加媒體
     *
     * @generated from field: map<string, recorder.URLMedia> map_mideas = 24;
     */
    mapMideas = {};
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.CurrentGame";
    static fields = proto3.util.newFieldList(() => [
        { no: 5, name: "game_code", kind: "scalar", T: 9 /* ScalarType.STRING */ },
        { no: 7, name: "shift", kind: "message", T: ShiftRecord, opt: true },
        { no: 9, name: "round", kind: "message", T: RoundRecord, opt: true },
        { no: 10, name: "shuffle", kind: "message", T: ShuffleRecord, opt: true },
        { no: 24, name: "map_mideas", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "message", T: URLMedia } },
    ]);
    static fromBinary(bytes, options) {
        return new CurrentGame().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new CurrentGame().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new CurrentGame().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(CurrentGame, a, b);
    }
}
/**
 * @generated from message recorder.FetchCurrentGameRequest
 */
export class FetchCurrentGameRequest extends Message {
    /**
     * 查詢的Table Code
     *
     * @generated from field: repeated string game_codes = 1;
     */
    gameCodes = [];
    /**
     * 返回Shift資訊
     *
     * @generated from field: bool shift = 7;
     */
    shift = false;
    /**
     * 返回Shuffle資訊
     *
     * @generated from field: bool shuffle = 10;
     */
    shuffle = false;
    /**
     * 返回直播網址
     *
     * @generated from field: bool stream = 3;
     */
    stream = false;
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.FetchCurrentGameRequest";
    static fields = proto3.util.newFieldList(() => [
        { no: 1, name: "game_codes", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
        { no: 7, name: "shift", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
        { no: 10, name: "shuffle", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
        { no: 3, name: "stream", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    ]);
    static fromBinary(bytes, options) {
        return new FetchCurrentGameRequest().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new FetchCurrentGameRequest().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new FetchCurrentGameRequest().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(FetchCurrentGameRequest, a, b);
    }
}
/**
 * @generated from message recorder.FetchCurrentGameResponse
 */
export class FetchCurrentGameResponse extends Message {
    /**
     * Table Code 對應的當下 Current Table
     *
     * @generated from field: map<string, recorder.CurrentGame> map_current_games = 1;
     */
    mapCurrentGames = {};
    /**
     * 時間戳
     *
     * @generated from field: google.protobuf.Timestamp ts = 2;
     */
    ts;
    constructor(data) {
        super();
        proto3.util.initPartial(data, this);
    }
    static runtime = proto3;
    static typeName = "recorder.FetchCurrentGameResponse";
    static fields = proto3.util.newFieldList(() => [
        { no: 1, name: "map_current_games", kind: "map", K: 9 /* ScalarType.STRING */, V: { kind: "message", T: CurrentGame } },
        { no: 2, name: "ts", kind: "message", T: Timestamp },
    ]);
    static fromBinary(bytes, options) {
        return new FetchCurrentGameResponse().fromBinary(bytes, options);
    }
    static fromJson(jsonValue, options) {
        return new FetchCurrentGameResponse().fromJson(jsonValue, options);
    }
    static fromJsonString(jsonString, options) {
        return new FetchCurrentGameResponse().fromJsonString(jsonString, options);
    }
    static equals(a, b) {
        return proto3.util.equals(FetchCurrentGameResponse, a, b);
    }
}
