// @generated by protoc-gen-connect-es v0.9.1
// @generated from file recorder/recorder.proto (package recorder, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RecordIDResponse, RecordRoadmapRequest, RecordRoundCancelRequest, RecordRoundFinishRequest, RecordRoundMediaRequest, RecordRoundResultsRequest, RecordRoundStartRequest, RecordRoundStepsRequest, RecordShiftEndedRequest, RecordShiftStartedRequest, RecordShuffleDoneRequest, RecordShuffleStartedRequest } from "./recorder_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service recorder.RecorderService
 */
export declare const RecorderService: {
  readonly typeName: "recorder.RecorderService",
  readonly methods: {
    /**
     * 建立新排班
     *
     * @generated from rpc recorder.RecorderService.RecordShiftStarted
     */
    readonly recordShiftStarted: {
      readonly name: "RecordShiftStarted",
      readonly I: typeof RecordShiftStartedRequest,
      readonly O: typeof RecordIDResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 排班結束
     *
     * @generated from rpc recorder.RecorderService.RecordShiftEnded
     */
    readonly recordShiftEnded: {
      readonly name: "RecordShiftEnded",
      readonly I: typeof RecordShiftEndedRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 開始更換牌組
     *
     * @generated from rpc recorder.RecorderService.RecordShuffleStarted
     */
    readonly recordShuffleStarted: {
      readonly name: "RecordShuffleStarted",
      readonly I: typeof RecordShuffleStartedRequest,
      readonly O: typeof RecordIDResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 更換牌組完畢
     *
     * @generated from rpc recorder.RecorderService.RecordShuffleDone
     */
    readonly recordShuffleDone: {
      readonly name: "RecordShuffleDone",
      readonly I: typeof RecordShuffleDoneRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 開啟新局
     *
     * @generated from rpc recorder.RecorderService.RecordRoundStart
     */
    readonly recordRoundStart: {
      readonly name: "RecordRoundStart",
      readonly I: typeof RecordRoundStartRequest,
      readonly O: typeof RecordIDResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 記錄步驟
     *
     * @generated from rpc recorder.RecorderService.RecordRoundSteps
     */
    readonly recordRoundSteps: {
      readonly name: "RecordRoundSteps",
      readonly I: typeof RecordRoundStepsRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 紀錄結果
     *
     * @generated from rpc recorder.RecorderService.RecordRoundResults
     */
    readonly recordRoundResults: {
      readonly name: "RecordRoundResults",
      readonly I: typeof RecordRoundResultsRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 此局作廢
     *
     * @generated from rpc recorder.RecorderService.RecordRoundCancel
     */
    readonly recordRoundCancel: {
      readonly name: "RecordRoundCancel",
      readonly I: typeof RecordRoundCancelRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 結束此局
     *
     * @generated from rpc recorder.RecorderService.RecordRoundFinish
     */
    readonly recordRoundFinish: {
      readonly name: "RecordRoundFinish",
      readonly I: typeof RecordRoundFinishRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 紀錄路紙
     *
     * @generated from rpc recorder.RecorderService.RecordRoadmap
     */
    readonly recordRoadmap: {
      readonly name: "RecordRoadmap",
      readonly I: typeof RecordRoadmapRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
    /**
     * 紀錄回放
     *
     * @generated from rpc recorder.RecorderService.RecordRoundVideo
     */
    readonly recordRoundVideo: {
      readonly name: "RecordRoundVideo",
      readonly I: typeof RecordRoundMediaRequest,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
  }
};

