// @generated by protoc-gen-es v1.3.1 with parameter "target=ts,import_extension=none"
// @generated from file cards/roulette.proto (package cards, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * 輪盤
 *
 * @generated from enum cards.Roulette
 */
export enum Roulette {
  /**
   * 未指定
   *
   * @generated from enum value: ROULETTE_CARD_UNSPECIFIED = 0;
   */
  ROULETTE_CARD_UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROULETTE_0 = 99;
   */
  ROULETTE_0 = 99,

  /**
   * @generated from enum value: ROULETTE_1 = 1;
   */
  ROULETTE_1 = 1,

  /**
   * @generated from enum value: ROULETTE_2 = 2;
   */
  ROULETTE_2 = 2,

  /**
   * @generated from enum value: ROULETTE_3 = 3;
   */
  ROULETTE_3 = 3,

  /**
   * @generated from enum value: ROULETTE_4 = 4;
   */
  ROULETTE_4 = 4,

  /**
   * @generated from enum value: ROULETTE_5 = 5;
   */
  ROULETTE_5 = 5,

  /**
   * @generated from enum value: ROULETTE_6 = 6;
   */
  ROULETTE_6 = 6,

  /**
   * @generated from enum value: ROULETTE_7 = 7;
   */
  ROULETTE_7 = 7,

  /**
   * @generated from enum value: ROULETTE_8 = 8;
   */
  ROULETTE_8 = 8,

  /**
   * @generated from enum value: ROULETTE_9 = 9;
   */
  ROULETTE_9 = 9,

  /**
   * @generated from enum value: ROULETTE_10 = 10;
   */
  ROULETTE_10 = 10,

  /**
   * @generated from enum value: ROULETTE_11 = 11;
   */
  ROULETTE_11 = 11,

  /**
   * @generated from enum value: ROULETTE_12 = 12;
   */
  ROULETTE_12 = 12,

  /**
   * @generated from enum value: ROULETTE_13 = 13;
   */
  ROULETTE_13 = 13,

  /**
   * @generated from enum value: ROULETTE_14 = 14;
   */
  ROULETTE_14 = 14,

  /**
   * @generated from enum value: ROULETTE_15 = 15;
   */
  ROULETTE_15 = 15,

  /**
   * @generated from enum value: ROULETTE_16 = 16;
   */
  ROULETTE_16 = 16,

  /**
   * @generated from enum value: ROULETTE_17 = 17;
   */
  ROULETTE_17 = 17,

  /**
   * @generated from enum value: ROULETTE_18 = 18;
   */
  ROULETTE_18 = 18,

  /**
   * @generated from enum value: ROULETTE_19 = 19;
   */
  ROULETTE_19 = 19,

  /**
   * @generated from enum value: ROULETTE_20 = 20;
   */
  ROULETTE_20 = 20,

  /**
   * @generated from enum value: ROULETTE_21 = 21;
   */
  ROULETTE_21 = 21,

  /**
   * @generated from enum value: ROULETTE_22 = 22;
   */
  ROULETTE_22 = 22,

  /**
   * @generated from enum value: ROULETTE_23 = 23;
   */
  ROULETTE_23 = 23,

  /**
   * @generated from enum value: ROULETTE_24 = 24;
   */
  ROULETTE_24 = 24,

  /**
   * @generated from enum value: ROULETTE_25 = 25;
   */
  ROULETTE_25 = 25,

  /**
   * @generated from enum value: ROULETTE_26 = 26;
   */
  ROULETTE_26 = 26,

  /**
   * @generated from enum value: ROULETTE_27 = 27;
   */
  ROULETTE_27 = 27,

  /**
   * @generated from enum value: ROULETTE_28 = 28;
   */
  ROULETTE_28 = 28,

  /**
   * @generated from enum value: ROULETTE_29 = 29;
   */
  ROULETTE_29 = 29,

  /**
   * @generated from enum value: ROULETTE_30 = 30;
   */
  ROULETTE_30 = 30,

  /**
   * @generated from enum value: ROULETTE_31 = 31;
   */
  ROULETTE_31 = 31,

  /**
   * @generated from enum value: ROULETTE_32 = 32;
   */
  ROULETTE_32 = 32,

  /**
   * @generated from enum value: ROULETTE_33 = 33;
   */
  ROULETTE_33 = 33,

  /**
   * @generated from enum value: ROULETTE_34 = 34;
   */
  ROULETTE_34 = 34,

  /**
   * @generated from enum value: ROULETTE_35 = 35;
   */
  ROULETTE_35 = 35,

  /**
   * @generated from enum value: ROULETTE_36 = 36;
   */
  ROULETTE_36 = 36,
}
// Retrieve enum metadata with: proto3.getEnumType(Roulette)
proto3.util.setEnumType(Roulette, "cards.Roulette", [
  { no: 0, name: "ROULETTE_CARD_UNSPECIFIED" },
  { no: 99, name: "ROULETTE_0" },
  { no: 1, name: "ROULETTE_1" },
  { no: 2, name: "ROULETTE_2" },
  { no: 3, name: "ROULETTE_3" },
  { no: 4, name: "ROULETTE_4" },
  { no: 5, name: "ROULETTE_5" },
  { no: 6, name: "ROULETTE_6" },
  { no: 7, name: "ROULETTE_7" },
  { no: 8, name: "ROULETTE_8" },
  { no: 9, name: "ROULETTE_9" },
  { no: 10, name: "ROULETTE_10" },
  { no: 11, name: "ROULETTE_11" },
  { no: 12, name: "ROULETTE_12" },
  { no: 13, name: "ROULETTE_13" },
  { no: 14, name: "ROULETTE_14" },
  { no: 15, name: "ROULETTE_15" },
  { no: 16, name: "ROULETTE_16" },
  { no: 17, name: "ROULETTE_17" },
  { no: 18, name: "ROULETTE_18" },
  { no: 19, name: "ROULETTE_19" },
  { no: 20, name: "ROULETTE_20" },
  { no: 21, name: "ROULETTE_21" },
  { no: 22, name: "ROULETTE_22" },
  { no: 23, name: "ROULETTE_23" },
  { no: 24, name: "ROULETTE_24" },
  { no: 25, name: "ROULETTE_25" },
  { no: 26, name: "ROULETTE_26" },
  { no: 27, name: "ROULETTE_27" },
  { no: 28, name: "ROULETTE_28" },
  { no: 29, name: "ROULETTE_29" },
  { no: 30, name: "ROULETTE_30" },
  { no: 31, name: "ROULETTE_31" },
  { no: 32, name: "ROULETTE_32" },
  { no: 33, name: "ROULETTE_33" },
  { no: 34, name: "ROULETTE_34" },
  { no: 35, name: "ROULETTE_35" },
  { no: 36, name: "ROULETTE_36" },
]);

