// @generated by protoc-gen-es v1.1.0 with parameter "target=ts,import_extension=none"
// @generated from file thebigbattle/record.proto (package thebigbattle, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum thebigbattle.CardStatus
 */
export enum CardStatus {
  /**
   * 未指定
   *
   * @generated from enum value: CARD_STATUS_UNSPECIFIED = 0;
   */
  CARD_STATUS_UNSPECIFIED = 0,

  /**
   * 翻開
   *
   * @generated from enum value: CARD_OPENED = 1;
   */
  CARD_OPENED = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(CardStatus)
proto3.util.setEnumType(CardStatus, "thebigbattle.CardStatus", [
  { no: 0, name: "CARD_STATUS_UNSPECIFIED" },
  { no: 1, name: "CARD_OPENED" },
]);

/**
 * 使用卡牌種類
 *
 * @generated from enum thebigbattle.CardType
 */
export enum CardType {
  /**
   * 未指定
   *
   * @generated from enum value: CARD_TYPE_UNSPECIFIED = 0;
   */
  CARD_TYPE_UNSPECIFIED = 0,

  /**
   * 撲克牌
   *
   * @generated from enum value: POKER = 1;
   */
  POKER = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(CardType)
proto3.util.setEnumType(CardType, "thebigbattle.CardType", [
  { no: 0, name: "CARD_TYPE_UNSPECIFIED" },
  { no: 1, name: "POKER" },
]);

/**
 * @generated from enum thebigbattle.ResourceType
 */
export enum ResourceType {
  /**
   * 未指定
   *
   * @generated from enum value: RESOURCE_TYPE_UNSPECIFIED = 0;
   */
  RESOURCE_TYPE_UNSPECIFIED = 0,

  /**
   * 例牌
   *
   * @generated from enum value: NORMAL = 1;
   */
  NORMAL = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(ResourceType)
proto3.util.setEnumType(ResourceType, "thebigbattle.ResourceType", [
  { no: 0, name: "RESOURCE_TYPE_UNSPECIFIED" },
  { no: 1, name: "NORMAL" },
]);

/**
 * 步驟，依據遊戲供應商邏輯，不是每個步驟都會走到
 *
 * @generated from enum thebigbattle.Step
 */
export enum Step {
  /**
   * 未指定
   *
   * @generated from enum value: STEP_UNSPECIFIED = 0;
   */
  STEP_UNSPECIFIED = 0,

  /**
   * 本局開始
   *
   * @generated from enum value: ROUND_START = 1;
   */
  ROUND_START = 1,

  /**
   * 本局完成
   *
   * @generated from enum value: ROUND_FINISHED = 2;
   */
  ROUND_FINISHED = 2,

  /**
   * 本局取消
   *
   * @generated from enum value: ROUND_CANCELED = 3;
   */
  ROUND_CANCELED = 3,

  /**
   * 派發龍例牌
   *
   * @generated from enum value: DEAL_DRAGON_1 = 4;
   */
  DEAL_DRAGON_1 = 4,

  /**
   * 派發虎例牌
   *
   * @generated from enum value: DEAL_TIGER_1 = 5;
   */
  DEAL_TIGER_1 = 5,

  /**
   * 開放下注
   *
   * @generated from enum value: OPEN_FOR_BETTING = 9;
   */
  OPEN_FOR_BETTING = 9,

  /**
   * 停止下注
   *
   * @generated from enum value: CLOSE_THE_BETTING = 10;
   */
  CLOSE_THE_BETTING = 10,

  /**
   * 開例牌
   *
   * @generated from enum value: SHOW_NORMAL = 12;
   */
  SHOW_NORMAL = 12,

  /**
   * PITBOSS 修改派發例牌
   *
   * @generated from enum value: PITBOSS_MODIFY_NORMAL = 24;
   */
  PITBOSS_MODIFY_NORMAL = 24,
}
// Retrieve enum metadata with: proto3.getEnumType(Step)
proto3.util.setEnumType(Step, "thebigbattle.Step", [
  { no: 0, name: "STEP_UNSPECIFIED" },
  { no: 1, name: "ROUND_START" },
  { no: 2, name: "ROUND_FINISHED" },
  { no: 3, name: "ROUND_CANCELED" },
  { no: 4, name: "DEAL_DRAGON_1" },
  { no: 5, name: "DEAL_TIGER_1" },
  { no: 9, name: "OPEN_FOR_BETTING" },
  { no: 10, name: "CLOSE_THE_BETTING" },
  { no: 12, name: "SHOW_NORMAL" },
  { no: 24, name: "PITBOSS_MODIFY_NORMAL" },
]);

/**
 * 座位功能代碼
 *
 * @generated from enum thebigbattle.Seat
 */
export enum Seat {
  /**
   * 未指定
   *
   * @generated from enum value: SEAT_UNSPECIFIED = 0;
   */
  SEAT_UNSPECIFIED = 0,

  /**
   * 龍
   *
   * @generated from enum value: DRAGON = 1;
   */
  DRAGON = 1,

  /**
   * 虎
   *
   * @generated from enum value: TIGER = 2;
   */
  TIGER = 2,

  /**
   * Dealer 
   *
   * @generated from enum value: DEALER = 3;
   */
  DEALER = 3,

  /**
   * Pitboss
   *
   * @generated from enum value: PITBOSS = 9;
   */
  PITBOSS = 9,
}
// Retrieve enum metadata with: proto3.getEnumType(Seat)
proto3.util.setEnumType(Seat, "thebigbattle.Seat", [
  { no: 0, name: "SEAT_UNSPECIFIED" },
  { no: 1, name: "DRAGON" },
  { no: 2, name: "TIGER" },
  { no: 3, name: "DEALER" },
  { no: 9, name: "PITBOSS" },
]);

/**
 * 結果紀錄類型代碼
 *
 * @generated from enum thebigbattle.ResultRecordType
 */
export enum ResultRecordType {
  /**
   * 未指定
   *
   * @generated from enum value: RESULT_RECORD_TYPE_UNSPECIFIED = 0;
   */
  RESULT_RECORD_TYPE_UNSPECIFIED = 0,

  /**
   * 遊戲局結束
   *
   * @generated from enum value: ROUND_FINISH = 1;
   */
  ROUND_FINISH = 1,

  /**
   * Pitboss 修正
   *
   * @generated from enum value: PITBOSS_MODIFY_RESULT = 2;
   */
  PITBOSS_MODIFY_RESULT = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(ResultRecordType)
proto3.util.setEnumType(ResultRecordType, "thebigbattle.ResultRecordType", [
  { no: 0, name: "RESULT_RECORD_TYPE_UNSPECIFIED" },
  { no: 1, name: "ROUND_FINISH" },
  { no: 2, name: "PITBOSS_MODIFY_RESULT" },
]);

/**
 * 取消原因
 *
 * @generated from enum thebigbattle.CancelReason
 */
export enum CancelReason {
  /**
   * 未指定，沒有取消
   *
   * @generated from enum value: CANCEL_REASON_UNSPECIFIED = 0;
   */
  CANCEL_REASON_UNSPECIFIED = 0,

  /**
   * 取消說明原因
   *
   * @generated from enum value: NO_REASON = 1;
   */
  NO_REASON = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(CancelReason)
proto3.util.setEnumType(CancelReason, "thebigbattle.CancelReason", [
  { no: 0, name: "CANCEL_REASON_UNSPECIFIED" },
  { no: 1, name: "NO_REASON" },
]);

