// @generated by protoc-gen-es v1.0.0 with parameter "target=ts,import_extension=none"
// @generated from file baccarat/record.proto (package baccarat, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * 使用卡牌種類
 *
 * @generated from enum baccarat.CardTypeCode
 */
export enum CardTypeCode {
  /**
   * 未指定
   *
   * @generated from enum value: CARD_TYPE_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * 撲克牌
   *
   * @generated from enum value: CARD_TYPE_CODE_POKER = 1;
   */
  POKER = 1,

  /**
   * 場控牌
   *
   * @generated from enum value: CARD_TYPE_CODE_CONTROL = 9;
   */
  CONTROL = 9,
}
// Retrieve enum metadata with: proto3.getEnumType(CardTypeCode)
proto3.util.setEnumType(CardTypeCode, "baccarat.CardTypeCode", [
  { no: 0, name: "CARD_TYPE_CODE_UNSPECIFIED" },
  { no: 1, name: "CARD_TYPE_CODE_POKER" },
  { no: 9, name: "CARD_TYPE_CODE_CONTROL" },
]);

/**
 * @generated from enum baccarat.ResourceTypeCode
 */
export enum ResourceTypeCode {
  /**
   * 未指定
   *
   * @generated from enum value: RESOURCE_TYPE_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * 手牌
   *
   * @generated from enum value: RESOURCE_TYPE_CODE_HAND_CARD = 1;
   */
  HAND_CARD = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(ResourceTypeCode)
proto3.util.setEnumType(ResourceTypeCode, "baccarat.ResourceTypeCode", [
  { no: 0, name: "RESOURCE_TYPE_CODE_UNSPECIFIED" },
  { no: 1, name: "RESOURCE_TYPE_CODE_HAND_CARD" },
]);

/**
 * 動作代碼
 *
 * @generated from enum baccarat.StepActionCode
 */
export enum StepActionCode {
  /**
   * 未指定
   *
   * @generated from enum value: STEP_ACTION_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * 派發閒家例牌
   *
   * @generated from enum value: STEP_ACTION_CODE_DEAL_PLAYER_NORMAL = 1;
   */
  DEAL_PLAYER_NORMAL = 1,

  /**
   * 派發莊家例牌
   *
   * @generated from enum value: STEP_ACTION_CODE_DEAL_BANKER_NORMAL = 2;
   */
  DEAL_BANKER_NORMAL = 2,

  /**
   * 開閒家例牌
   *
   * @generated from enum value: STEP_ACTION_CODE_SHOW_PLAYER_NORMAL = 3;
   */
  SHOW_PLAYER_NORMAL = 3,

  /**
   * 開莊家例牌
   *
   * @generated from enum value: STEP_ACTION_CODE_SHOW_BANKER_NORMAL = 4;
   */
  SHOW_BANKER_NORMAL = 4,

  /**
   * 補閒家
   *
   * @generated from enum value: STEP_ACTION_CODE_DEAL_PLAYER_UNNORMAL = 5;
   */
  DEAL_PLAYER_UNNORMAL = 5,

  /**
   * 補莊家
   *
   * @generated from enum value: STEP_ACTION_CODE_DEAL_BANKER_UNNORMAL = 6;
   */
  DEAL_BANKER_UNNORMAL = 6,

  /**
   * PITBOSS
   *
   * @generated from enum value: STEP_ACTION_CODE_PITBOSS_MODIFY = 9;
   */
  PITBOSS_MODIFY = 9,
}
// Retrieve enum metadata with: proto3.getEnumType(StepActionCode)
proto3.util.setEnumType(StepActionCode, "baccarat.StepActionCode", [
  { no: 0, name: "STEP_ACTION_CODE_UNSPECIFIED" },
  { no: 1, name: "STEP_ACTION_CODE_DEAL_PLAYER_NORMAL" },
  { no: 2, name: "STEP_ACTION_CODE_DEAL_BANKER_NORMAL" },
  { no: 3, name: "STEP_ACTION_CODE_SHOW_PLAYER_NORMAL" },
  { no: 4, name: "STEP_ACTION_CODE_SHOW_BANKER_NORMAL" },
  { no: 5, name: "STEP_ACTION_CODE_DEAL_PLAYER_UNNORMAL" },
  { no: 6, name: "STEP_ACTION_CODE_DEAL_BANKER_UNNORMAL" },
  { no: 9, name: "STEP_ACTION_CODE_PITBOSS_MODIFY" },
]);

/**
 * 步驟代碼
 *
 * @generated from enum baccarat.StepCode
 */
export enum StepCode {
  /**
   * 未指定
   *
   * @generated from enum value: STEP_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * 派發例牌
   *
   * @generated from enum value: STEP_CODE_DEAL_NORMAL = 1;
   */
  DEAL_NORMAL = 1,

  /**
   * 開例牌
   *
   * @generated from enum value: STEP_CODE_SHOW_NORMAL = 2;
   */
  SHOW_NORMAL = 2,

  /**
   * 補閒家
   *
   * @generated from enum value: STEP_CODE_DEAL_PLAYER_UNNORMAL = 3;
   */
  DEAL_PLAYER_UNNORMAL = 3,

  /**
   * 補莊家
   *
   * @generated from enum value: STEP_CODE_DEAL_BANKER_UNNORMAL = 4;
   */
  DEAL_BANKER_UNNORMAL = 4,

  /**
   * PITBOSS
   *
   * @generated from enum value: STEP_CODE_PITBOSS_MODIFY = 9;
   */
  PITBOSS_MODIFY = 9,
}
// Retrieve enum metadata with: proto3.getEnumType(StepCode)
proto3.util.setEnumType(StepCode, "baccarat.StepCode", [
  { no: 0, name: "STEP_CODE_UNSPECIFIED" },
  { no: 1, name: "STEP_CODE_DEAL_NORMAL" },
  { no: 2, name: "STEP_CODE_SHOW_NORMAL" },
  { no: 3, name: "STEP_CODE_DEAL_PLAYER_UNNORMAL" },
  { no: 4, name: "STEP_CODE_DEAL_BANKER_UNNORMAL" },
  { no: 9, name: "STEP_CODE_PITBOSS_MODIFY" },
]);

/**
 * 座位功能代碼
 *
 * @generated from enum baccarat.SeatCode
 */
export enum SeatCode {
  /**
   * 未指定
   *
   * @generated from enum value: SEAT_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * 莊家
   *
   * @generated from enum value: SEAT_CODE_SEAT_BANKER = 1;
   */
  SEAT_BANKER = 1,

  /**
   * 閒家
   *
   * @generated from enum value: SEAT_CODE_SEAT_PLAYER = 2;
   */
  SEAT_PLAYER = 2,

  /**
   * Dealer 
   *
   * @generated from enum value: SEAT_CODE_SEAT_DEALER = 3;
   */
  SEAT_DEALER = 3,

  /**
   * Pitboss
   *
   * @generated from enum value: SEAT_CODE_SEAT_PITBOSS = 9;
   */
  SEAT_PITBOSS = 9,
}
// Retrieve enum metadata with: proto3.getEnumType(SeatCode)
proto3.util.setEnumType(SeatCode, "baccarat.SeatCode", [
  { no: 0, name: "SEAT_CODE_UNSPECIFIED" },
  { no: 1, name: "SEAT_CODE_SEAT_BANKER" },
  { no: 2, name: "SEAT_CODE_SEAT_PLAYER" },
  { no: 3, name: "SEAT_CODE_SEAT_DEALER" },
  { no: 9, name: "SEAT_CODE_SEAT_PITBOSS" },
]);

/**
 * 結果紀錄類型代碼
 *
 * @generated from enum baccarat.ResultRecordTypeCode
 */
export enum ResultRecordTypeCode {
  /**
   * 未指定
   *
   * @generated from enum value: RESULT_RECORD_TYPE_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * 遊戲局結束
   *
   * @generated from enum value: RESULT_RECORD_TYPE_CODE_ROUND_FINISH = 1;
   */
  ROUND_FINISH = 1,

  /**
   * Pitboss 修正
   *
   * @generated from enum value: RESULT_RECORD_TYPE_CODE_PITBOSS_JUDGEMENT = 2;
   */
  PITBOSS_JUDGEMENT = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(ResultRecordTypeCode)
proto3.util.setEnumType(ResultRecordTypeCode, "baccarat.ResultRecordTypeCode", [
  { no: 0, name: "RESULT_RECORD_TYPE_CODE_UNSPECIFIED" },
  { no: 1, name: "RESULT_RECORD_TYPE_CODE_ROUND_FINISH" },
  { no: 2, name: "RESULT_RECORD_TYPE_CODE_PITBOSS_JUDGEMENT" },
]);

/**
 * @generated from enum baccarat.CancelReasonCode
 */
export enum CancelReasonCode {
  /**
   * 未指定，沒有取消
   *
   * @generated from enum value: CANCEL_REASON_CODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * 取消說明原因
   *
   * @generated from enum value: CANCEL_REASON_CODE_NO_REASON = 1;
   */
  NO_REASON = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(CancelReasonCode)
proto3.util.setEnumType(CancelReasonCode, "baccarat.CancelReasonCode", [
  { no: 0, name: "CANCEL_REASON_CODE_UNSPECIFIED" },
  { no: 1, name: "CANCEL_REASON_CODE_NO_REASON" },
]);

