// @generated by protoc-gen-es v1.2.0 with parameter "target=ts,import_extension=none"
// @generated from file fantan/fantan.proto (package fantan, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * 番攤
 *
 * @generated from enum fantan.Fantan
 */
export enum Fantan {
  /**
   * 未指定
   *
   * @generated from enum value: DICE_CARD_UNSPECIFIED = 0;
   */
  DICE_CARD_UNSPECIFIED = 0,

  /**
   * @generated from enum value: DICE_AMOUNT_1 = 1;
   */
  DICE_AMOUNT_1 = 1,

  /**
   * @generated from enum value: DICE_AMOUNT_2 = 2;
   */
  DICE_AMOUNT_2 = 2,

  /**
   * @generated from enum value: DICE_AMOUNT_3 = 3;
   */
  DICE_AMOUNT_3 = 3,

  /**
   * @generated from enum value: DICE_AMOUNT_4 = 4;
   */
  DICE_AMOUNT_4 = 4,

  /**
   * @generated from enum value: DICE_AMOUNT_5 = 5;
   */
  DICE_AMOUNT_5 = 5,

  /**
   * @generated from enum value: DICE_AMOUNT_6 = 6;
   */
  DICE_AMOUNT_6 = 6,

  /**
   * @generated from enum value: DICE_AMOUNT_7 = 7;
   */
  DICE_AMOUNT_7 = 7,

  /**
   * @generated from enum value: DICE_AMOUNT_8 = 8;
   */
  DICE_AMOUNT_8 = 8,

  /**
   * @generated from enum value: DICE_AMOUNT_9 = 9;
   */
  DICE_AMOUNT_9 = 9,

  /**
   * @generated from enum value: DICE_AMOUNT_10 = 10;
   */
  DICE_AMOUNT_10 = 10,

  /**
   * @generated from enum value: DICE_AMOUNT_11 = 11;
   */
  DICE_AMOUNT_11 = 11,

  /**
   * @generated from enum value: DICE_AMOUNT_12 = 12;
   */
  DICE_AMOUNT_12 = 12,

  /**
   * @generated from enum value: DICE_AMOUNT_13 = 13;
   */
  DICE_AMOUNT_13 = 13,

  /**
   * @generated from enum value: DICE_AMOUNT_14 = 14;
   */
  DICE_AMOUNT_14 = 14,

  /**
   * @generated from enum value: DICE_AMOUNT_15 = 15;
   */
  DICE_AMOUNT_15 = 15,

  /**
   * @generated from enum value: DICE_AMOUNT_16 = 16;
   */
  DICE_AMOUNT_16 = 16,

  /**
   * @generated from enum value: DICE_AMOUNT_17 = 17;
   */
  DICE_AMOUNT_17 = 17,

  /**
   * @generated from enum value: DICE_AMOUNT_18 = 18;
   */
  DICE_AMOUNT_18 = 18,

  /**
   * @generated from enum value: DICE_AMOUNT_19 = 19;
   */
  DICE_AMOUNT_19 = 19,

  /**
   * @generated from enum value: DICE_AMOUNT_20 = 20;
   */
  DICE_AMOUNT_20 = 20,

  /**
   * @generated from enum value: DICE_AMOUNT_21 = 21;
   */
  DICE_AMOUNT_21 = 21,

  /**
   * @generated from enum value: DICE_AMOUNT_22 = 22;
   */
  DICE_AMOUNT_22 = 22,

  /**
   * @generated from enum value: DICE_AMOUNT_23 = 23;
   */
  DICE_AMOUNT_23 = 23,

  /**
   * @generated from enum value: DICE_AMOUNT_24 = 24;
   */
  DICE_AMOUNT_24 = 24,

  /**
   * @generated from enum value: DICE_AMOUNT_25 = 25;
   */
  DICE_AMOUNT_25 = 25,

  /**
   * @generated from enum value: DICE_AMOUNT_26 = 26;
   */
  DICE_AMOUNT_26 = 26,

  /**
   * @generated from enum value: DICE_AMOUNT_27 = 27;
   */
  DICE_AMOUNT_27 = 27,

  /**
   * @generated from enum value: DICE_AMOUNT_28 = 28;
   */
  DICE_AMOUNT_28 = 28,

  /**
   * @generated from enum value: DICE_AMOUNT_29 = 29;
   */
  DICE_AMOUNT_29 = 29,

  /**
   * @generated from enum value: DICE_AMOUNT_30 = 30;
   */
  DICE_AMOUNT_30 = 30,

  /**
   * @generated from enum value: DICE_AMOUNT_31 = 31;
   */
  DICE_AMOUNT_31 = 31,

  /**
   * @generated from enum value: DICE_AMOUNT_32 = 32;
   */
  DICE_AMOUNT_32 = 32,

  /**
   * @generated from enum value: DICE_AMOUNT_33 = 33;
   */
  DICE_AMOUNT_33 = 33,

  /**
   * @generated from enum value: DICE_AMOUNT_34 = 34;
   */
  DICE_AMOUNT_34 = 34,

  /**
   * @generated from enum value: DICE_AMOUNT_35 = 35;
   */
  DICE_AMOUNT_35 = 35,

  /**
   * @generated from enum value: DICE_AMOUNT_36 = 36;
   */
  DICE_AMOUNT_36 = 36,

  /**
   * @generated from enum value: DICE_AMOUNT_37 = 37;
   */
  DICE_AMOUNT_37 = 37,

  /**
   * @generated from enum value: DICE_AMOUNT_38 = 38;
   */
  DICE_AMOUNT_38 = 38,

  /**
   * @generated from enum value: DICE_AMOUNT_39 = 39;
   */
  DICE_AMOUNT_39 = 39,

  /**
   * @generated from enum value: DICE_AMOUNT_40 = 40;
   */
  DICE_AMOUNT_40 = 40,

  /**
   * @generated from enum value: DICE_AMOUNT_41 = 41;
   */
  DICE_AMOUNT_41 = 41,

  /**
   * @generated from enum value: DICE_AMOUNT_42 = 42;
   */
  DICE_AMOUNT_42 = 42,

  /**
   * @generated from enum value: DICE_AMOUNT_43 = 43;
   */
  DICE_AMOUNT_43 = 43,

  /**
   * @generated from enum value: DICE_AMOUNT_44 = 44;
   */
  DICE_AMOUNT_44 = 44,

  /**
   * @generated from enum value: DICE_AMOUNT_45 = 45;
   */
  DICE_AMOUNT_45 = 45,

  /**
   * @generated from enum value: DICE_AMOUNT_46 = 46;
   */
  DICE_AMOUNT_46 = 46,

  /**
   * @generated from enum value: DICE_AMOUNT_47 = 47;
   */
  DICE_AMOUNT_47 = 47,

  /**
   * @generated from enum value: DICE_AMOUNT_48 = 48;
   */
  DICE_AMOUNT_48 = 48,

  /**
   * @generated from enum value: DICE_AMOUNT_49 = 49;
   */
  DICE_AMOUNT_49 = 49,

  /**
   * @generated from enum value: DICE_AMOUNT_50 = 50;
   */
  DICE_AMOUNT_50 = 50,

  /**
   * @generated from enum value: DICE_AMOUNT_51 = 51;
   */
  DICE_AMOUNT_51 = 51,

  /**
   * @generated from enum value: DICE_AMOUNT_52 = 52;
   */
  DICE_AMOUNT_52 = 52,

  /**
   * @generated from enum value: DICE_AMOUNT_53 = 53;
   */
  DICE_AMOUNT_53 = 53,

  /**
   * @generated from enum value: DICE_AMOUNT_54 = 54;
   */
  DICE_AMOUNT_54 = 54,

  /**
   * @generated from enum value: DICE_AMOUNT_55 = 55;
   */
  DICE_AMOUNT_55 = 55,

  /**
   * @generated from enum value: DICE_AMOUNT_56 = 56;
   */
  DICE_AMOUNT_56 = 56,

  /**
   * @generated from enum value: DICE_AMOUNT_57 = 57;
   */
  DICE_AMOUNT_57 = 57,

  /**
   * @generated from enum value: DICE_AMOUNT_58 = 58;
   */
  DICE_AMOUNT_58 = 58,

  /**
   * @generated from enum value: DICE_AMOUNT_59 = 59;
   */
  DICE_AMOUNT_59 = 59,

  /**
   * @generated from enum value: DICE_AMOUNT_60 = 60;
   */
  DICE_AMOUNT_60 = 60,

  /**
   * @generated from enum value: DICE_AMOUNT_61 = 61;
   */
  DICE_AMOUNT_61 = 61,

  /**
   * @generated from enum value: DICE_AMOUNT_62 = 62;
   */
  DICE_AMOUNT_62 = 62,

  /**
   * @generated from enum value: DICE_AMOUNT_63 = 63;
   */
  DICE_AMOUNT_63 = 63,

  /**
   * @generated from enum value: DICE_AMOUNT_64 = 64;
   */
  DICE_AMOUNT_64 = 64,

  /**
   * @generated from enum value: DICE_AMOUNT_65 = 65;
   */
  DICE_AMOUNT_65 = 65,

  /**
   * @generated from enum value: DICE_AMOUNT_66 = 66;
   */
  DICE_AMOUNT_66 = 66,

  /**
   * @generated from enum value: DICE_AMOUNT_67 = 67;
   */
  DICE_AMOUNT_67 = 67,

  /**
   * @generated from enum value: DICE_AMOUNT_68 = 68;
   */
  DICE_AMOUNT_68 = 68,

  /**
   * @generated from enum value: DICE_AMOUNT_69 = 69;
   */
  DICE_AMOUNT_69 = 69,

  /**
   * @generated from enum value: DICE_AMOUNT_70 = 70;
   */
  DICE_AMOUNT_70 = 70,

  /**
   * @generated from enum value: DICE_AMOUNT_71 = 71;
   */
  DICE_AMOUNT_71 = 71,

  /**
   * @generated from enum value: DICE_AMOUNT_72 = 72;
   */
  DICE_AMOUNT_72 = 72,

  /**
   * @generated from enum value: DICE_AMOUNT_73 = 73;
   */
  DICE_AMOUNT_73 = 73,

  /**
   * @generated from enum value: DICE_AMOUNT_74 = 74;
   */
  DICE_AMOUNT_74 = 74,

  /**
   * @generated from enum value: DICE_AMOUNT_75 = 75;
   */
  DICE_AMOUNT_75 = 75,

  /**
   * @generated from enum value: DICE_AMOUNT_76 = 76;
   */
  DICE_AMOUNT_76 = 76,

  /**
   * @generated from enum value: DICE_AMOUNT_77 = 77;
   */
  DICE_AMOUNT_77 = 77,

  /**
   * @generated from enum value: DICE_AMOUNT_78 = 78;
   */
  DICE_AMOUNT_78 = 78,

  /**
   * @generated from enum value: DICE_AMOUNT_79 = 79;
   */
  DICE_AMOUNT_79 = 79,

  /**
   * @generated from enum value: DICE_AMOUNT_80 = 80;
   */
  DICE_AMOUNT_80 = 80,

  /**
   * @generated from enum value: DICE_AMOUNT_81 = 81;
   */
  DICE_AMOUNT_81 = 81,

  /**
   * @generated from enum value: DICE_AMOUNT_82 = 82;
   */
  DICE_AMOUNT_82 = 82,

  /**
   * @generated from enum value: DICE_AMOUNT_83 = 83;
   */
  DICE_AMOUNT_83 = 83,

  /**
   * @generated from enum value: DICE_AMOUNT_84 = 84;
   */
  DICE_AMOUNT_84 = 84,

  /**
   * @generated from enum value: DICE_AMOUNT_85 = 85;
   */
  DICE_AMOUNT_85 = 85,

  /**
   * @generated from enum value: DICE_AMOUNT_86 = 86;
   */
  DICE_AMOUNT_86 = 86,

  /**
   * @generated from enum value: DICE_AMOUNT_87 = 87;
   */
  DICE_AMOUNT_87 = 87,

  /**
   * @generated from enum value: DICE_AMOUNT_88 = 88;
   */
  DICE_AMOUNT_88 = 88,

  /**
   * @generated from enum value: DICE_AMOUNT_89 = 89;
   */
  DICE_AMOUNT_89 = 89,

  /**
   * @generated from enum value: DICE_AMOUNT_90 = 90;
   */
  DICE_AMOUNT_90 = 90,

  /**
   * @generated from enum value: DICE_AMOUNT_91 = 91;
   */
  DICE_AMOUNT_91 = 91,

  /**
   * @generated from enum value: DICE_AMOUNT_92 = 92;
   */
  DICE_AMOUNT_92 = 92,

  /**
   * @generated from enum value: DICE_AMOUNT_93 = 93;
   */
  DICE_AMOUNT_93 = 93,

  /**
   * @generated from enum value: DICE_AMOUNT_94 = 94;
   */
  DICE_AMOUNT_94 = 94,

  /**
   * @generated from enum value: DICE_AMOUNT_95 = 95;
   */
  DICE_AMOUNT_95 = 95,

  /**
   * @generated from enum value: DICE_AMOUNT_96 = 96;
   */
  DICE_AMOUNT_96 = 96,

  /**
   * @generated from enum value: DICE_AMOUNT_97 = 97;
   */
  DICE_AMOUNT_97 = 97,

  /**
   * @generated from enum value: DICE_AMOUNT_98 = 98;
   */
  DICE_AMOUNT_98 = 98,

  /**
   * @generated from enum value: DICE_AMOUNT_99 = 99;
   */
  DICE_AMOUNT_99 = 99,

  /**
   * @generated from enum value: DICE_AMOUNT_100 = 100;
   */
  DICE_AMOUNT_100 = 100,

  /**
   * @generated from enum value: DICE_AMOUNT_101 = 101;
   */
  DICE_AMOUNT_101 = 101,

  /**
   * @generated from enum value: DICE_AMOUNT_102 = 102;
   */
  DICE_AMOUNT_102 = 102,

  /**
   * @generated from enum value: DICE_AMOUNT_103 = 103;
   */
  DICE_AMOUNT_103 = 103,

  /**
   * @generated from enum value: DICE_AMOUNT_104 = 104;
   */
  DICE_AMOUNT_104 = 104,

  /**
   * @generated from enum value: DICE_AMOUNT_105 = 105;
   */
  DICE_AMOUNT_105 = 105,

  /**
   * @generated from enum value: DICE_AMOUNT_106 = 106;
   */
  DICE_AMOUNT_106 = 106,

  /**
   * @generated from enum value: DICE_AMOUNT_107 = 107;
   */
  DICE_AMOUNT_107 = 107,

  /**
   * @generated from enum value: DICE_AMOUNT_108 = 108;
   */
  DICE_AMOUNT_108 = 108,

  /**
   * @generated from enum value: DICE_AMOUNT_109 = 109;
   */
  DICE_AMOUNT_109 = 109,

  /**
   * @generated from enum value: DICE_AMOUNT_110 = 110;
   */
  DICE_AMOUNT_110 = 110,

  /**
   * @generated from enum value: DICE_AMOUNT_111 = 111;
   */
  DICE_AMOUNT_111 = 111,

  /**
   * @generated from enum value: DICE_AMOUNT_112 = 112;
   */
  DICE_AMOUNT_112 = 112,

  /**
   * @generated from enum value: DICE_AMOUNT_113 = 113;
   */
  DICE_AMOUNT_113 = 113,

  /**
   * @generated from enum value: DICE_AMOUNT_114 = 114;
   */
  DICE_AMOUNT_114 = 114,

  /**
   * @generated from enum value: DICE_AMOUNT_115 = 115;
   */
  DICE_AMOUNT_115 = 115,

  /**
   * @generated from enum value: DICE_AMOUNT_116 = 116;
   */
  DICE_AMOUNT_116 = 116,

  /**
   * @generated from enum value: DICE_AMOUNT_117 = 117;
   */
  DICE_AMOUNT_117 = 117,

  /**
   * @generated from enum value: DICE_AMOUNT_118 = 118;
   */
  DICE_AMOUNT_118 = 118,

  /**
   * @generated from enum value: DICE_AMOUNT_119 = 119;
   */
  DICE_AMOUNT_119 = 119,

  /**
   * @generated from enum value: DICE_AMOUNT_120 = 120;
   */
  DICE_AMOUNT_120 = 120,

  /**
   * @generated from enum value: DICE_AMOUNT_121 = 121;
   */
  DICE_AMOUNT_121 = 121,

  /**
   * @generated from enum value: DICE_AMOUNT_122 = 122;
   */
  DICE_AMOUNT_122 = 122,

  /**
   * @generated from enum value: DICE_AMOUNT_123 = 123;
   */
  DICE_AMOUNT_123 = 123,

  /**
   * @generated from enum value: DICE_AMOUNT_124 = 124;
   */
  DICE_AMOUNT_124 = 124,

  /**
   * @generated from enum value: DICE_AMOUNT_125 = 125;
   */
  DICE_AMOUNT_125 = 125,

  /**
   * @generated from enum value: DICE_AMOUNT_126 = 126;
   */
  DICE_AMOUNT_126 = 126,

  /**
   * @generated from enum value: DICE_AMOUNT_127 = 127;
   */
  DICE_AMOUNT_127 = 127,

  /**
   * @generated from enum value: DICE_AMOUNT_128 = 128;
   */
  DICE_AMOUNT_128 = 128,

  /**
   * @generated from enum value: DICE_AMOUNT_129 = 129;
   */
  DICE_AMOUNT_129 = 129,

  /**
   * @generated from enum value: DICE_AMOUNT_130 = 130;
   */
  DICE_AMOUNT_130 = 130,

  /**
   * @generated from enum value: DICE_AMOUNT_131 = 131;
   */
  DICE_AMOUNT_131 = 131,

  /**
   * @generated from enum value: DICE_AMOUNT_132 = 132;
   */
  DICE_AMOUNT_132 = 132,

  /**
   * @generated from enum value: DICE_AMOUNT_133 = 133;
   */
  DICE_AMOUNT_133 = 133,

  /**
   * @generated from enum value: DICE_AMOUNT_134 = 134;
   */
  DICE_AMOUNT_134 = 134,

  /**
   * @generated from enum value: DICE_AMOUNT_135 = 135;
   */
  DICE_AMOUNT_135 = 135,

  /**
   * @generated from enum value: DICE_AMOUNT_136 = 136;
   */
  DICE_AMOUNT_136 = 136,

  /**
   * @generated from enum value: DICE_AMOUNT_137 = 137;
   */
  DICE_AMOUNT_137 = 137,

  /**
   * @generated from enum value: DICE_AMOUNT_138 = 138;
   */
  DICE_AMOUNT_138 = 138,

  /**
   * @generated from enum value: DICE_AMOUNT_139 = 139;
   */
  DICE_AMOUNT_139 = 139,

  /**
   * @generated from enum value: DICE_AMOUNT_140 = 140;
   */
  DICE_AMOUNT_140 = 140,

  /**
   * @generated from enum value: DICE_AMOUNT_141 = 141;
   */
  DICE_AMOUNT_141 = 141,

  /**
   * @generated from enum value: DICE_AMOUNT_142 = 142;
   */
  DICE_AMOUNT_142 = 142,

  /**
   * @generated from enum value: DICE_AMOUNT_143 = 143;
   */
  DICE_AMOUNT_143 = 143,

  /**
   * @generated from enum value: DICE_AMOUNT_144 = 144;
   */
  DICE_AMOUNT_144 = 144,

  /**
   * @generated from enum value: DICE_AMOUNT_145 = 145;
   */
  DICE_AMOUNT_145 = 145,

  /**
   * @generated from enum value: DICE_AMOUNT_146 = 146;
   */
  DICE_AMOUNT_146 = 146,

  /**
   * @generated from enum value: DICE_AMOUNT_147 = 147;
   */
  DICE_AMOUNT_147 = 147,

  /**
   * @generated from enum value: DICE_AMOUNT_148 = 148;
   */
  DICE_AMOUNT_148 = 148,

  /**
   * @generated from enum value: DICE_AMOUNT_149 = 149;
   */
  DICE_AMOUNT_149 = 149,

  /**
   * @generated from enum value: DICE_AMOUNT_150 = 150;
   */
  DICE_AMOUNT_150 = 150,

  /**
   * @generated from enum value: DICE_AMOUNT_151 = 151;
   */
  DICE_AMOUNT_151 = 151,

  /**
   * @generated from enum value: DICE_AMOUNT_152 = 152;
   */
  DICE_AMOUNT_152 = 152,

  /**
   * @generated from enum value: DICE_AMOUNT_153 = 153;
   */
  DICE_AMOUNT_153 = 153,

  /**
   * @generated from enum value: DICE_AMOUNT_154 = 154;
   */
  DICE_AMOUNT_154 = 154,

  /**
   * @generated from enum value: DICE_AMOUNT_155 = 155;
   */
  DICE_AMOUNT_155 = 155,

  /**
   * @generated from enum value: DICE_AMOUNT_156 = 156;
   */
  DICE_AMOUNT_156 = 156,

  /**
   * @generated from enum value: DICE_AMOUNT_157 = 157;
   */
  DICE_AMOUNT_157 = 157,

  /**
   * @generated from enum value: DICE_AMOUNT_158 = 158;
   */
  DICE_AMOUNT_158 = 158,

  /**
   * @generated from enum value: DICE_AMOUNT_159 = 159;
   */
  DICE_AMOUNT_159 = 159,

  /**
   * @generated from enum value: DICE_AMOUNT_160 = 160;
   */
  DICE_AMOUNT_160 = 160,

  /**
   * @generated from enum value: DICE_AMOUNT_161 = 161;
   */
  DICE_AMOUNT_161 = 161,

  /**
   * @generated from enum value: DICE_AMOUNT_162 = 162;
   */
  DICE_AMOUNT_162 = 162,

  /**
   * @generated from enum value: DICE_AMOUNT_163 = 163;
   */
  DICE_AMOUNT_163 = 163,

  /**
   * @generated from enum value: DICE_AMOUNT_164 = 164;
   */
  DICE_AMOUNT_164 = 164,

  /**
   * @generated from enum value: DICE_AMOUNT_165 = 165;
   */
  DICE_AMOUNT_165 = 165,

  /**
   * @generated from enum value: DICE_AMOUNT_166 = 166;
   */
  DICE_AMOUNT_166 = 166,

  /**
   * @generated from enum value: DICE_AMOUNT_167 = 167;
   */
  DICE_AMOUNT_167 = 167,

  /**
   * @generated from enum value: DICE_AMOUNT_168 = 168;
   */
  DICE_AMOUNT_168 = 168,

  /**
   * @generated from enum value: DICE_AMOUNT_169 = 169;
   */
  DICE_AMOUNT_169 = 169,

  /**
   * @generated from enum value: DICE_AMOUNT_170 = 170;
   */
  DICE_AMOUNT_170 = 170,

  /**
   * @generated from enum value: DICE_AMOUNT_171 = 171;
   */
  DICE_AMOUNT_171 = 171,

  /**
   * @generated from enum value: DICE_AMOUNT_172 = 172;
   */
  DICE_AMOUNT_172 = 172,

  /**
   * @generated from enum value: DICE_AMOUNT_173 = 173;
   */
  DICE_AMOUNT_173 = 173,

  /**
   * @generated from enum value: DICE_AMOUNT_174 = 174;
   */
  DICE_AMOUNT_174 = 174,

  /**
   * @generated from enum value: DICE_AMOUNT_175 = 175;
   */
  DICE_AMOUNT_175 = 175,

  /**
   * @generated from enum value: DICE_AMOUNT_176 = 176;
   */
  DICE_AMOUNT_176 = 176,

  /**
   * @generated from enum value: DICE_AMOUNT_177 = 177;
   */
  DICE_AMOUNT_177 = 177,

  /**
   * @generated from enum value: DICE_AMOUNT_178 = 178;
   */
  DICE_AMOUNT_178 = 178,

  /**
   * @generated from enum value: DICE_AMOUNT_179 = 179;
   */
  DICE_AMOUNT_179 = 179,

  /**
   * @generated from enum value: DICE_AMOUNT_180 = 180;
   */
  DICE_AMOUNT_180 = 180,

  /**
   * @generated from enum value: DICE_AMOUNT_181 = 181;
   */
  DICE_AMOUNT_181 = 181,

  /**
   * @generated from enum value: DICE_AMOUNT_182 = 182;
   */
  DICE_AMOUNT_182 = 182,

  /**
   * @generated from enum value: DICE_AMOUNT_183 = 183;
   */
  DICE_AMOUNT_183 = 183,

  /**
   * @generated from enum value: DICE_AMOUNT_184 = 184;
   */
  DICE_AMOUNT_184 = 184,

  /**
   * @generated from enum value: DICE_AMOUNT_185 = 185;
   */
  DICE_AMOUNT_185 = 185,

  /**
   * @generated from enum value: DICE_AMOUNT_186 = 186;
   */
  DICE_AMOUNT_186 = 186,

  /**
   * @generated from enum value: DICE_AMOUNT_187 = 187;
   */
  DICE_AMOUNT_187 = 187,

  /**
   * @generated from enum value: DICE_AMOUNT_188 = 188;
   */
  DICE_AMOUNT_188 = 188,

  /**
   * @generated from enum value: DICE_AMOUNT_189 = 189;
   */
  DICE_AMOUNT_189 = 189,

  /**
   * @generated from enum value: DICE_AMOUNT_190 = 190;
   */
  DICE_AMOUNT_190 = 190,

  /**
   * @generated from enum value: DICE_AMOUNT_191 = 191;
   */
  DICE_AMOUNT_191 = 191,

  /**
   * @generated from enum value: DICE_AMOUNT_192 = 192;
   */
  DICE_AMOUNT_192 = 192,

  /**
   * @generated from enum value: DICE_AMOUNT_193 = 193;
   */
  DICE_AMOUNT_193 = 193,

  /**
   * @generated from enum value: DICE_AMOUNT_194 = 194;
   */
  DICE_AMOUNT_194 = 194,

  /**
   * @generated from enum value: DICE_AMOUNT_195 = 195;
   */
  DICE_AMOUNT_195 = 195,

  /**
   * @generated from enum value: DICE_AMOUNT_196 = 196;
   */
  DICE_AMOUNT_196 = 196,

  /**
   * @generated from enum value: DICE_AMOUNT_197 = 197;
   */
  DICE_AMOUNT_197 = 197,

  /**
   * @generated from enum value: DICE_AMOUNT_198 = 198;
   */
  DICE_AMOUNT_198 = 198,

  /**
   * @generated from enum value: DICE_AMOUNT_199 = 199;
   */
  DICE_AMOUNT_199 = 199,

  /**
   * @generated from enum value: DICE_AMOUNT_200 = 200;
   */
  DICE_AMOUNT_200 = 200,

  /**
   * @generated from enum value: DICE_AMOUNT_201 = 201;
   */
  DICE_AMOUNT_201 = 201,

  /**
   * @generated from enum value: DICE_AMOUNT_202 = 202;
   */
  DICE_AMOUNT_202 = 202,

  /**
   * @generated from enum value: DICE_AMOUNT_203 = 203;
   */
  DICE_AMOUNT_203 = 203,

  /**
   * @generated from enum value: DICE_AMOUNT_204 = 204;
   */
  DICE_AMOUNT_204 = 204,

  /**
   * @generated from enum value: DICE_AMOUNT_205 = 205;
   */
  DICE_AMOUNT_205 = 205,

  /**
   * @generated from enum value: DICE_AMOUNT_206 = 206;
   */
  DICE_AMOUNT_206 = 206,

  /**
   * @generated from enum value: DICE_AMOUNT_207 = 207;
   */
  DICE_AMOUNT_207 = 207,

  /**
   * @generated from enum value: DICE_AMOUNT_208 = 208;
   */
  DICE_AMOUNT_208 = 208,

  /**
   * @generated from enum value: DICE_AMOUNT_209 = 209;
   */
  DICE_AMOUNT_209 = 209,

  /**
   * @generated from enum value: DICE_AMOUNT_210 = 210;
   */
  DICE_AMOUNT_210 = 210,

  /**
   * @generated from enum value: DICE_AMOUNT_211 = 211;
   */
  DICE_AMOUNT_211 = 211,

  /**
   * @generated from enum value: DICE_AMOUNT_212 = 212;
   */
  DICE_AMOUNT_212 = 212,

  /**
   * @generated from enum value: DICE_AMOUNT_213 = 213;
   */
  DICE_AMOUNT_213 = 213,

  /**
   * @generated from enum value: DICE_AMOUNT_214 = 214;
   */
  DICE_AMOUNT_214 = 214,

  /**
   * @generated from enum value: DICE_AMOUNT_215 = 215;
   */
  DICE_AMOUNT_215 = 215,

  /**
   * @generated from enum value: DICE_AMOUNT_216 = 216;
   */
  DICE_AMOUNT_216 = 216,

  /**
   * @generated from enum value: DICE_AMOUNT_217 = 217;
   */
  DICE_AMOUNT_217 = 217,

  /**
   * @generated from enum value: DICE_AMOUNT_218 = 218;
   */
  DICE_AMOUNT_218 = 218,

  /**
   * @generated from enum value: DICE_AMOUNT_219 = 219;
   */
  DICE_AMOUNT_219 = 219,

  /**
   * @generated from enum value: DICE_AMOUNT_220 = 220;
   */
  DICE_AMOUNT_220 = 220,

  /**
   * @generated from enum value: DICE_AMOUNT_221 = 221;
   */
  DICE_AMOUNT_221 = 221,

  /**
   * @generated from enum value: DICE_AMOUNT_222 = 222;
   */
  DICE_AMOUNT_222 = 222,

  /**
   * @generated from enum value: DICE_AMOUNT_223 = 223;
   */
  DICE_AMOUNT_223 = 223,

  /**
   * @generated from enum value: DICE_AMOUNT_224 = 224;
   */
  DICE_AMOUNT_224 = 224,

  /**
   * @generated from enum value: DICE_AMOUNT_225 = 225;
   */
  DICE_AMOUNT_225 = 225,

  /**
   * @generated from enum value: DICE_AMOUNT_226 = 226;
   */
  DICE_AMOUNT_226 = 226,

  /**
   * @generated from enum value: DICE_AMOUNT_227 = 227;
   */
  DICE_AMOUNT_227 = 227,

  /**
   * @generated from enum value: DICE_AMOUNT_228 = 228;
   */
  DICE_AMOUNT_228 = 228,

  /**
   * @generated from enum value: DICE_AMOUNT_229 = 229;
   */
  DICE_AMOUNT_229 = 229,

  /**
   * @generated from enum value: DICE_AMOUNT_230 = 230;
   */
  DICE_AMOUNT_230 = 230,

  /**
   * @generated from enum value: DICE_AMOUNT_231 = 231;
   */
  DICE_AMOUNT_231 = 231,

  /**
   * @generated from enum value: DICE_AMOUNT_232 = 232;
   */
  DICE_AMOUNT_232 = 232,

  /**
   * @generated from enum value: DICE_AMOUNT_233 = 233;
   */
  DICE_AMOUNT_233 = 233,

  /**
   * @generated from enum value: DICE_AMOUNT_234 = 234;
   */
  DICE_AMOUNT_234 = 234,

  /**
   * @generated from enum value: DICE_AMOUNT_235 = 235;
   */
  DICE_AMOUNT_235 = 235,

  /**
   * @generated from enum value: DICE_AMOUNT_236 = 236;
   */
  DICE_AMOUNT_236 = 236,

  /**
   * @generated from enum value: DICE_AMOUNT_237 = 237;
   */
  DICE_AMOUNT_237 = 237,

  /**
   * @generated from enum value: DICE_AMOUNT_238 = 238;
   */
  DICE_AMOUNT_238 = 238,

  /**
   * @generated from enum value: DICE_AMOUNT_239 = 239;
   */
  DICE_AMOUNT_239 = 239,

  /**
   * @generated from enum value: DICE_AMOUNT_240 = 240;
   */
  DICE_AMOUNT_240 = 240,

  /**
   * @generated from enum value: DICE_AMOUNT_241 = 241;
   */
  DICE_AMOUNT_241 = 241,

  /**
   * @generated from enum value: DICE_AMOUNT_242 = 242;
   */
  DICE_AMOUNT_242 = 242,

  /**
   * @generated from enum value: DICE_AMOUNT_243 = 243;
   */
  DICE_AMOUNT_243 = 243,

  /**
   * @generated from enum value: DICE_AMOUNT_244 = 244;
   */
  DICE_AMOUNT_244 = 244,

  /**
   * @generated from enum value: DICE_AMOUNT_245 = 245;
   */
  DICE_AMOUNT_245 = 245,

  /**
   * @generated from enum value: DICE_AMOUNT_246 = 246;
   */
  DICE_AMOUNT_246 = 246,

  /**
   * @generated from enum value: DICE_AMOUNT_247 = 247;
   */
  DICE_AMOUNT_247 = 247,

  /**
   * @generated from enum value: DICE_AMOUNT_248 = 248;
   */
  DICE_AMOUNT_248 = 248,

  /**
   * @generated from enum value: DICE_AMOUNT_249 = 249;
   */
  DICE_AMOUNT_249 = 249,

  /**
   * @generated from enum value: DICE_AMOUNT_250 = 250;
   */
  DICE_AMOUNT_250 = 250,

  /**
   * @generated from enum value: DICE_AMOUNT_251 = 251;
   */
  DICE_AMOUNT_251 = 251,

  /**
   * @generated from enum value: DICE_AMOUNT_252 = 252;
   */
  DICE_AMOUNT_252 = 252,

  /**
   * @generated from enum value: DICE_AMOUNT_253 = 253;
   */
  DICE_AMOUNT_253 = 253,

  /**
   * @generated from enum value: DICE_AMOUNT_254 = 254;
   */
  DICE_AMOUNT_254 = 254,

  /**
   * @generated from enum value: DICE_AMOUNT_255 = 255;
   */
  DICE_AMOUNT_255 = 255,

  /**
   * @generated from enum value: DICE_AMOUNT_256 = 256;
   */
  DICE_AMOUNT_256 = 256,

  /**
   * @generated from enum value: DICE_AMOUNT_257 = 257;
   */
  DICE_AMOUNT_257 = 257,

  /**
   * @generated from enum value: DICE_AMOUNT_258 = 258;
   */
  DICE_AMOUNT_258 = 258,

  /**
   * @generated from enum value: DICE_AMOUNT_259 = 259;
   */
  DICE_AMOUNT_259 = 259,

  /**
   * @generated from enum value: DICE_AMOUNT_260 = 260;
   */
  DICE_AMOUNT_260 = 260,

  /**
   * @generated from enum value: DICE_AMOUNT_261 = 261;
   */
  DICE_AMOUNT_261 = 261,

  /**
   * @generated from enum value: DICE_AMOUNT_262 = 262;
   */
  DICE_AMOUNT_262 = 262,

  /**
   * @generated from enum value: DICE_AMOUNT_263 = 263;
   */
  DICE_AMOUNT_263 = 263,

  /**
   * @generated from enum value: DICE_AMOUNT_264 = 264;
   */
  DICE_AMOUNT_264 = 264,

  /**
   * @generated from enum value: DICE_AMOUNT_265 = 265;
   */
  DICE_AMOUNT_265 = 265,

  /**
   * @generated from enum value: DICE_AMOUNT_266 = 266;
   */
  DICE_AMOUNT_266 = 266,

  /**
   * @generated from enum value: DICE_AMOUNT_267 = 267;
   */
  DICE_AMOUNT_267 = 267,

  /**
   * @generated from enum value: DICE_AMOUNT_268 = 268;
   */
  DICE_AMOUNT_268 = 268,

  /**
   * @generated from enum value: DICE_AMOUNT_269 = 269;
   */
  DICE_AMOUNT_269 = 269,

  /**
   * @generated from enum value: DICE_AMOUNT_270 = 270;
   */
  DICE_AMOUNT_270 = 270,

  /**
   * @generated from enum value: DICE_AMOUNT_271 = 271;
   */
  DICE_AMOUNT_271 = 271,

  /**
   * @generated from enum value: DICE_AMOUNT_272 = 272;
   */
  DICE_AMOUNT_272 = 272,

  /**
   * @generated from enum value: DICE_AMOUNT_273 = 273;
   */
  DICE_AMOUNT_273 = 273,

  /**
   * @generated from enum value: DICE_AMOUNT_274 = 274;
   */
  DICE_AMOUNT_274 = 274,

  /**
   * @generated from enum value: DICE_AMOUNT_275 = 275;
   */
  DICE_AMOUNT_275 = 275,

  /**
   * @generated from enum value: DICE_AMOUNT_276 = 276;
   */
  DICE_AMOUNT_276 = 276,

  /**
   * @generated from enum value: DICE_AMOUNT_277 = 277;
   */
  DICE_AMOUNT_277 = 277,

  /**
   * @generated from enum value: DICE_AMOUNT_278 = 278;
   */
  DICE_AMOUNT_278 = 278,

  /**
   * @generated from enum value: DICE_AMOUNT_279 = 279;
   */
  DICE_AMOUNT_279 = 279,

  /**
   * @generated from enum value: DICE_AMOUNT_280 = 280;
   */
  DICE_AMOUNT_280 = 280,

  /**
   * @generated from enum value: DICE_AMOUNT_281 = 281;
   */
  DICE_AMOUNT_281 = 281,

  /**
   * @generated from enum value: DICE_AMOUNT_282 = 282;
   */
  DICE_AMOUNT_282 = 282,

  /**
   * @generated from enum value: DICE_AMOUNT_283 = 283;
   */
  DICE_AMOUNT_283 = 283,

  /**
   * @generated from enum value: DICE_AMOUNT_284 = 284;
   */
  DICE_AMOUNT_284 = 284,

  /**
   * @generated from enum value: DICE_AMOUNT_285 = 285;
   */
  DICE_AMOUNT_285 = 285,

  /**
   * @generated from enum value: DICE_AMOUNT_286 = 286;
   */
  DICE_AMOUNT_286 = 286,

  /**
   * @generated from enum value: DICE_AMOUNT_287 = 287;
   */
  DICE_AMOUNT_287 = 287,

  /**
   * @generated from enum value: DICE_AMOUNT_288 = 288;
   */
  DICE_AMOUNT_288 = 288,

  /**
   * @generated from enum value: DICE_AMOUNT_289 = 289;
   */
  DICE_AMOUNT_289 = 289,

  /**
   * @generated from enum value: DICE_AMOUNT_290 = 290;
   */
  DICE_AMOUNT_290 = 290,

  /**
   * @generated from enum value: DICE_AMOUNT_291 = 291;
   */
  DICE_AMOUNT_291 = 291,

  /**
   * @generated from enum value: DICE_AMOUNT_292 = 292;
   */
  DICE_AMOUNT_292 = 292,

  /**
   * @generated from enum value: DICE_AMOUNT_293 = 293;
   */
  DICE_AMOUNT_293 = 293,

  /**
   * @generated from enum value: DICE_AMOUNT_294 = 294;
   */
  DICE_AMOUNT_294 = 294,

  /**
   * @generated from enum value: DICE_AMOUNT_295 = 295;
   */
  DICE_AMOUNT_295 = 295,

  /**
   * @generated from enum value: DICE_AMOUNT_296 = 296;
   */
  DICE_AMOUNT_296 = 296,

  /**
   * @generated from enum value: DICE_AMOUNT_297 = 297;
   */
  DICE_AMOUNT_297 = 297,

  /**
   * @generated from enum value: DICE_AMOUNT_298 = 298;
   */
  DICE_AMOUNT_298 = 298,

  /**
   * @generated from enum value: DICE_AMOUNT_299 = 299;
   */
  DICE_AMOUNT_299 = 299,

  /**
   * @generated from enum value: DICE_AMOUNT_300 = 300;
   */
  DICE_AMOUNT_300 = 300,
}
// Retrieve enum metadata with: proto3.getEnumType(Fantan)
proto3.util.setEnumType(Fantan, "fantan.Fantan", [
  { no: 0, name: "DICE_CARD_UNSPECIFIED" },
  { no: 1, name: "DICE_AMOUNT_1" },
  { no: 2, name: "DICE_AMOUNT_2" },
  { no: 3, name: "DICE_AMOUNT_3" },
  { no: 4, name: "DICE_AMOUNT_4" },
  { no: 5, name: "DICE_AMOUNT_5" },
  { no: 6, name: "DICE_AMOUNT_6" },
  { no: 7, name: "DICE_AMOUNT_7" },
  { no: 8, name: "DICE_AMOUNT_8" },
  { no: 9, name: "DICE_AMOUNT_9" },
  { no: 10, name: "DICE_AMOUNT_10" },
  { no: 11, name: "DICE_AMOUNT_11" },
  { no: 12, name: "DICE_AMOUNT_12" },
  { no: 13, name: "DICE_AMOUNT_13" },
  { no: 14, name: "DICE_AMOUNT_14" },
  { no: 15, name: "DICE_AMOUNT_15" },
  { no: 16, name: "DICE_AMOUNT_16" },
  { no: 17, name: "DICE_AMOUNT_17" },
  { no: 18, name: "DICE_AMOUNT_18" },
  { no: 19, name: "DICE_AMOUNT_19" },
  { no: 20, name: "DICE_AMOUNT_20" },
  { no: 21, name: "DICE_AMOUNT_21" },
  { no: 22, name: "DICE_AMOUNT_22" },
  { no: 23, name: "DICE_AMOUNT_23" },
  { no: 24, name: "DICE_AMOUNT_24" },
  { no: 25, name: "DICE_AMOUNT_25" },
  { no: 26, name: "DICE_AMOUNT_26" },
  { no: 27, name: "DICE_AMOUNT_27" },
  { no: 28, name: "DICE_AMOUNT_28" },
  { no: 29, name: "DICE_AMOUNT_29" },
  { no: 30, name: "DICE_AMOUNT_30" },
  { no: 31, name: "DICE_AMOUNT_31" },
  { no: 32, name: "DICE_AMOUNT_32" },
  { no: 33, name: "DICE_AMOUNT_33" },
  { no: 34, name: "DICE_AMOUNT_34" },
  { no: 35, name: "DICE_AMOUNT_35" },
  { no: 36, name: "DICE_AMOUNT_36" },
  { no: 37, name: "DICE_AMOUNT_37" },
  { no: 38, name: "DICE_AMOUNT_38" },
  { no: 39, name: "DICE_AMOUNT_39" },
  { no: 40, name: "DICE_AMOUNT_40" },
  { no: 41, name: "DICE_AMOUNT_41" },
  { no: 42, name: "DICE_AMOUNT_42" },
  { no: 43, name: "DICE_AMOUNT_43" },
  { no: 44, name: "DICE_AMOUNT_44" },
  { no: 45, name: "DICE_AMOUNT_45" },
  { no: 46, name: "DICE_AMOUNT_46" },
  { no: 47, name: "DICE_AMOUNT_47" },
  { no: 48, name: "DICE_AMOUNT_48" },
  { no: 49, name: "DICE_AMOUNT_49" },
  { no: 50, name: "DICE_AMOUNT_50" },
  { no: 51, name: "DICE_AMOUNT_51" },
  { no: 52, name: "DICE_AMOUNT_52" },
  { no: 53, name: "DICE_AMOUNT_53" },
  { no: 54, name: "DICE_AMOUNT_54" },
  { no: 55, name: "DICE_AMOUNT_55" },
  { no: 56, name: "DICE_AMOUNT_56" },
  { no: 57, name: "DICE_AMOUNT_57" },
  { no: 58, name: "DICE_AMOUNT_58" },
  { no: 59, name: "DICE_AMOUNT_59" },
  { no: 60, name: "DICE_AMOUNT_60" },
  { no: 61, name: "DICE_AMOUNT_61" },
  { no: 62, name: "DICE_AMOUNT_62" },
  { no: 63, name: "DICE_AMOUNT_63" },
  { no: 64, name: "DICE_AMOUNT_64" },
  { no: 65, name: "DICE_AMOUNT_65" },
  { no: 66, name: "DICE_AMOUNT_66" },
  { no: 67, name: "DICE_AMOUNT_67" },
  { no: 68, name: "DICE_AMOUNT_68" },
  { no: 69, name: "DICE_AMOUNT_69" },
  { no: 70, name: "DICE_AMOUNT_70" },
  { no: 71, name: "DICE_AMOUNT_71" },
  { no: 72, name: "DICE_AMOUNT_72" },
  { no: 73, name: "DICE_AMOUNT_73" },
  { no: 74, name: "DICE_AMOUNT_74" },
  { no: 75, name: "DICE_AMOUNT_75" },
  { no: 76, name: "DICE_AMOUNT_76" },
  { no: 77, name: "DICE_AMOUNT_77" },
  { no: 78, name: "DICE_AMOUNT_78" },
  { no: 79, name: "DICE_AMOUNT_79" },
  { no: 80, name: "DICE_AMOUNT_80" },
  { no: 81, name: "DICE_AMOUNT_81" },
  { no: 82, name: "DICE_AMOUNT_82" },
  { no: 83, name: "DICE_AMOUNT_83" },
  { no: 84, name: "DICE_AMOUNT_84" },
  { no: 85, name: "DICE_AMOUNT_85" },
  { no: 86, name: "DICE_AMOUNT_86" },
  { no: 87, name: "DICE_AMOUNT_87" },
  { no: 88, name: "DICE_AMOUNT_88" },
  { no: 89, name: "DICE_AMOUNT_89" },
  { no: 90, name: "DICE_AMOUNT_90" },
  { no: 91, name: "DICE_AMOUNT_91" },
  { no: 92, name: "DICE_AMOUNT_92" },
  { no: 93, name: "DICE_AMOUNT_93" },
  { no: 94, name: "DICE_AMOUNT_94" },
  { no: 95, name: "DICE_AMOUNT_95" },
  { no: 96, name: "DICE_AMOUNT_96" },
  { no: 97, name: "DICE_AMOUNT_97" },
  { no: 98, name: "DICE_AMOUNT_98" },
  { no: 99, name: "DICE_AMOUNT_99" },
  { no: 100, name: "DICE_AMOUNT_100" },
  { no: 101, name: "DICE_AMOUNT_101" },
  { no: 102, name: "DICE_AMOUNT_102" },
  { no: 103, name: "DICE_AMOUNT_103" },
  { no: 104, name: "DICE_AMOUNT_104" },
  { no: 105, name: "DICE_AMOUNT_105" },
  { no: 106, name: "DICE_AMOUNT_106" },
  { no: 107, name: "DICE_AMOUNT_107" },
  { no: 108, name: "DICE_AMOUNT_108" },
  { no: 109, name: "DICE_AMOUNT_109" },
  { no: 110, name: "DICE_AMOUNT_110" },
  { no: 111, name: "DICE_AMOUNT_111" },
  { no: 112, name: "DICE_AMOUNT_112" },
  { no: 113, name: "DICE_AMOUNT_113" },
  { no: 114, name: "DICE_AMOUNT_114" },
  { no: 115, name: "DICE_AMOUNT_115" },
  { no: 116, name: "DICE_AMOUNT_116" },
  { no: 117, name: "DICE_AMOUNT_117" },
  { no: 118, name: "DICE_AMOUNT_118" },
  { no: 119, name: "DICE_AMOUNT_119" },
  { no: 120, name: "DICE_AMOUNT_120" },
  { no: 121, name: "DICE_AMOUNT_121" },
  { no: 122, name: "DICE_AMOUNT_122" },
  { no: 123, name: "DICE_AMOUNT_123" },
  { no: 124, name: "DICE_AMOUNT_124" },
  { no: 125, name: "DICE_AMOUNT_125" },
  { no: 126, name: "DICE_AMOUNT_126" },
  { no: 127, name: "DICE_AMOUNT_127" },
  { no: 128, name: "DICE_AMOUNT_128" },
  { no: 129, name: "DICE_AMOUNT_129" },
  { no: 130, name: "DICE_AMOUNT_130" },
  { no: 131, name: "DICE_AMOUNT_131" },
  { no: 132, name: "DICE_AMOUNT_132" },
  { no: 133, name: "DICE_AMOUNT_133" },
  { no: 134, name: "DICE_AMOUNT_134" },
  { no: 135, name: "DICE_AMOUNT_135" },
  { no: 136, name: "DICE_AMOUNT_136" },
  { no: 137, name: "DICE_AMOUNT_137" },
  { no: 138, name: "DICE_AMOUNT_138" },
  { no: 139, name: "DICE_AMOUNT_139" },
  { no: 140, name: "DICE_AMOUNT_140" },
  { no: 141, name: "DICE_AMOUNT_141" },
  { no: 142, name: "DICE_AMOUNT_142" },
  { no: 143, name: "DICE_AMOUNT_143" },
  { no: 144, name: "DICE_AMOUNT_144" },
  { no: 145, name: "DICE_AMOUNT_145" },
  { no: 146, name: "DICE_AMOUNT_146" },
  { no: 147, name: "DICE_AMOUNT_147" },
  { no: 148, name: "DICE_AMOUNT_148" },
  { no: 149, name: "DICE_AMOUNT_149" },
  { no: 150, name: "DICE_AMOUNT_150" },
  { no: 151, name: "DICE_AMOUNT_151" },
  { no: 152, name: "DICE_AMOUNT_152" },
  { no: 153, name: "DICE_AMOUNT_153" },
  { no: 154, name: "DICE_AMOUNT_154" },
  { no: 155, name: "DICE_AMOUNT_155" },
  { no: 156, name: "DICE_AMOUNT_156" },
  { no: 157, name: "DICE_AMOUNT_157" },
  { no: 158, name: "DICE_AMOUNT_158" },
  { no: 159, name: "DICE_AMOUNT_159" },
  { no: 160, name: "DICE_AMOUNT_160" },
  { no: 161, name: "DICE_AMOUNT_161" },
  { no: 162, name: "DICE_AMOUNT_162" },
  { no: 163, name: "DICE_AMOUNT_163" },
  { no: 164, name: "DICE_AMOUNT_164" },
  { no: 165, name: "DICE_AMOUNT_165" },
  { no: 166, name: "DICE_AMOUNT_166" },
  { no: 167, name: "DICE_AMOUNT_167" },
  { no: 168, name: "DICE_AMOUNT_168" },
  { no: 169, name: "DICE_AMOUNT_169" },
  { no: 170, name: "DICE_AMOUNT_170" },
  { no: 171, name: "DICE_AMOUNT_171" },
  { no: 172, name: "DICE_AMOUNT_172" },
  { no: 173, name: "DICE_AMOUNT_173" },
  { no: 174, name: "DICE_AMOUNT_174" },
  { no: 175, name: "DICE_AMOUNT_175" },
  { no: 176, name: "DICE_AMOUNT_176" },
  { no: 177, name: "DICE_AMOUNT_177" },
  { no: 178, name: "DICE_AMOUNT_178" },
  { no: 179, name: "DICE_AMOUNT_179" },
  { no: 180, name: "DICE_AMOUNT_180" },
  { no: 181, name: "DICE_AMOUNT_181" },
  { no: 182, name: "DICE_AMOUNT_182" },
  { no: 183, name: "DICE_AMOUNT_183" },
  { no: 184, name: "DICE_AMOUNT_184" },
  { no: 185, name: "DICE_AMOUNT_185" },
  { no: 186, name: "DICE_AMOUNT_186" },
  { no: 187, name: "DICE_AMOUNT_187" },
  { no: 188, name: "DICE_AMOUNT_188" },
  { no: 189, name: "DICE_AMOUNT_189" },
  { no: 190, name: "DICE_AMOUNT_190" },
  { no: 191, name: "DICE_AMOUNT_191" },
  { no: 192, name: "DICE_AMOUNT_192" },
  { no: 193, name: "DICE_AMOUNT_193" },
  { no: 194, name: "DICE_AMOUNT_194" },
  { no: 195, name: "DICE_AMOUNT_195" },
  { no: 196, name: "DICE_AMOUNT_196" },
  { no: 197, name: "DICE_AMOUNT_197" },
  { no: 198, name: "DICE_AMOUNT_198" },
  { no: 199, name: "DICE_AMOUNT_199" },
  { no: 200, name: "DICE_AMOUNT_200" },
  { no: 201, name: "DICE_AMOUNT_201" },
  { no: 202, name: "DICE_AMOUNT_202" },
  { no: 203, name: "DICE_AMOUNT_203" },
  { no: 204, name: "DICE_AMOUNT_204" },
  { no: 205, name: "DICE_AMOUNT_205" },
  { no: 206, name: "DICE_AMOUNT_206" },
  { no: 207, name: "DICE_AMOUNT_207" },
  { no: 208, name: "DICE_AMOUNT_208" },
  { no: 209, name: "DICE_AMOUNT_209" },
  { no: 210, name: "DICE_AMOUNT_210" },
  { no: 211, name: "DICE_AMOUNT_211" },
  { no: 212, name: "DICE_AMOUNT_212" },
  { no: 213, name: "DICE_AMOUNT_213" },
  { no: 214, name: "DICE_AMOUNT_214" },
  { no: 215, name: "DICE_AMOUNT_215" },
  { no: 216, name: "DICE_AMOUNT_216" },
  { no: 217, name: "DICE_AMOUNT_217" },
  { no: 218, name: "DICE_AMOUNT_218" },
  { no: 219, name: "DICE_AMOUNT_219" },
  { no: 220, name: "DICE_AMOUNT_220" },
  { no: 221, name: "DICE_AMOUNT_221" },
  { no: 222, name: "DICE_AMOUNT_222" },
  { no: 223, name: "DICE_AMOUNT_223" },
  { no: 224, name: "DICE_AMOUNT_224" },
  { no: 225, name: "DICE_AMOUNT_225" },
  { no: 226, name: "DICE_AMOUNT_226" },
  { no: 227, name: "DICE_AMOUNT_227" },
  { no: 228, name: "DICE_AMOUNT_228" },
  { no: 229, name: "DICE_AMOUNT_229" },
  { no: 230, name: "DICE_AMOUNT_230" },
  { no: 231, name: "DICE_AMOUNT_231" },
  { no: 232, name: "DICE_AMOUNT_232" },
  { no: 233, name: "DICE_AMOUNT_233" },
  { no: 234, name: "DICE_AMOUNT_234" },
  { no: 235, name: "DICE_AMOUNT_235" },
  { no: 236, name: "DICE_AMOUNT_236" },
  { no: 237, name: "DICE_AMOUNT_237" },
  { no: 238, name: "DICE_AMOUNT_238" },
  { no: 239, name: "DICE_AMOUNT_239" },
  { no: 240, name: "DICE_AMOUNT_240" },
  { no: 241, name: "DICE_AMOUNT_241" },
  { no: 242, name: "DICE_AMOUNT_242" },
  { no: 243, name: "DICE_AMOUNT_243" },
  { no: 244, name: "DICE_AMOUNT_244" },
  { no: 245, name: "DICE_AMOUNT_245" },
  { no: 246, name: "DICE_AMOUNT_246" },
  { no: 247, name: "DICE_AMOUNT_247" },
  { no: 248, name: "DICE_AMOUNT_248" },
  { no: 249, name: "DICE_AMOUNT_249" },
  { no: 250, name: "DICE_AMOUNT_250" },
  { no: 251, name: "DICE_AMOUNT_251" },
  { no: 252, name: "DICE_AMOUNT_252" },
  { no: 253, name: "DICE_AMOUNT_253" },
  { no: 254, name: "DICE_AMOUNT_254" },
  { no: 255, name: "DICE_AMOUNT_255" },
  { no: 256, name: "DICE_AMOUNT_256" },
  { no: 257, name: "DICE_AMOUNT_257" },
  { no: 258, name: "DICE_AMOUNT_258" },
  { no: 259, name: "DICE_AMOUNT_259" },
  { no: 260, name: "DICE_AMOUNT_260" },
  { no: 261, name: "DICE_AMOUNT_261" },
  { no: 262, name: "DICE_AMOUNT_262" },
  { no: 263, name: "DICE_AMOUNT_263" },
  { no: 264, name: "DICE_AMOUNT_264" },
  { no: 265, name: "DICE_AMOUNT_265" },
  { no: 266, name: "DICE_AMOUNT_266" },
  { no: 267, name: "DICE_AMOUNT_267" },
  { no: 268, name: "DICE_AMOUNT_268" },
  { no: 269, name: "DICE_AMOUNT_269" },
  { no: 270, name: "DICE_AMOUNT_270" },
  { no: 271, name: "DICE_AMOUNT_271" },
  { no: 272, name: "DICE_AMOUNT_272" },
  { no: 273, name: "DICE_AMOUNT_273" },
  { no: 274, name: "DICE_AMOUNT_274" },
  { no: 275, name: "DICE_AMOUNT_275" },
  { no: 276, name: "DICE_AMOUNT_276" },
  { no: 277, name: "DICE_AMOUNT_277" },
  { no: 278, name: "DICE_AMOUNT_278" },
  { no: 279, name: "DICE_AMOUNT_279" },
  { no: 280, name: "DICE_AMOUNT_280" },
  { no: 281, name: "DICE_AMOUNT_281" },
  { no: 282, name: "DICE_AMOUNT_282" },
  { no: 283, name: "DICE_AMOUNT_283" },
  { no: 284, name: "DICE_AMOUNT_284" },
  { no: 285, name: "DICE_AMOUNT_285" },
  { no: 286, name: "DICE_AMOUNT_286" },
  { no: 287, name: "DICE_AMOUNT_287" },
  { no: 288, name: "DICE_AMOUNT_288" },
  { no: 289, name: "DICE_AMOUNT_289" },
  { no: 290, name: "DICE_AMOUNT_290" },
  { no: 291, name: "DICE_AMOUNT_291" },
  { no: 292, name: "DICE_AMOUNT_292" },
  { no: 293, name: "DICE_AMOUNT_293" },
  { no: 294, name: "DICE_AMOUNT_294" },
  { no: 295, name: "DICE_AMOUNT_295" },
  { no: 296, name: "DICE_AMOUNT_296" },
  { no: 297, name: "DICE_AMOUNT_297" },
  { no: 298, name: "DICE_AMOUNT_298" },
  { no: 299, name: "DICE_AMOUNT_299" },
  { no: 300, name: "DICE_AMOUNT_300" },
]);

